[package]
name = "cartesian_tree"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
proconio = { version = "0.5.0", features = ["derive"] }
cartesian-tree = { path = "../../../tree/cartesian-tree" }
