[package]
name = "alds1_14_b"
version = "0.1.0"
edition = "2024"

[dependencies]
proconio = { version = "0.5.0", features = ["derive"] }
mersenne-modint = { path = '../../../math/mersenne-modint' }
rolling-hash-segment-tree = { path = '../../../string/rolling-hash-segment-tree' }
