[package]
name = "grl_1_c"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
proconio = { version = "0.5.0", features = ["derive"] }
warshall-floyd = { path = "../../../graph/warshall-floyd" }
