[package]
name = "dsl_1_a"
version = "0.1.0"
edition = "2024"

[dependencies]
proconio = { version = "0.5.0", features = ["derive"] }
query = { path = '../../../macro/query' }
union-find = { path = "../../../data-structure/union-find" }
