[package]
name = "volume28-2880"
version = "0.1.0"
edition = "2024"

[dependencies]
proconio = { version = "0.5.0", features = ["derive"] }
interval-set = { path = "../../../data-structure/interval-set" }
