[package]
name = "grl_5_c"
version = "0.1.0"
edition = "2024"

[dependencies]
proconio = { version = "0.5.0", features = ["derive"] }
heavy-light-decomposition = { path = "../../../tree/heavy-light-decomposition" }
