[package]
name = "dpl_5_d"
version = "0.1.0"
edition = "2024"

[dependencies]
proconio = { version = "0.5.0", features = ["derive"] }
combinatorics = { path = "../../../math/combinatorics" }
modint = { path = "../../../math/modint" }
