[package]
name = "dsl_2_i"
version = "0.1.0"
edition = "2024"

[dependencies]
proconio = { version = "0.5.0", features = ["derive"] }
query = { path = '../../../macro/query' }
lazy-segment-tree = { path = '../../../data-structure/lazy-segment-tree' }
