[package]
name = "number_of_substrings"
version = "0.1.0"
edition = "2024"

[dependencies]
proconio = { version = "0.5.0", features = ["derive"] }
lcp-array = { path = "../../../string/lcp-array" }
suffix-array = { path = "../../../string/suffix-array" }
